### ISSUE TITLE
windows support

### ISSUE THREAD

**Issue by sudityashrivastav** [MatthewAraujo/update-golang#1]
Add a feature to update Golang in windows.

**Comment by MatthewAraujo** [comment]
i see you

**Comment by MatthewAraujo** [comment]
Sorry brother, i tried, not gonna happen

**Comment by sudityashrivastav** [comment]
> Sorry brother, i tried, not gonna happen

I will add 2 features.

1. Install Golang(If a user want to install).
2. Update Golang(if a user want to update).

After adding these features I'll send a pull request.

One more thing... In your readme file you specified that we need Golang installed to run the code. This is not true because Golang provides native executable for all the os.

**Comment by MatthewAraujo** [comment]
That's true, but I didn’t include the binary in this repo. I prefer that you install it using `go install`. If you already have the binary, that’s fine, but I’m not providing it here.
